# Generated by Django 6.1 on 2026-08-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blog_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
