# Generated by Django 6.1 on 2026-09-14 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_disliked_by_post_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='disliked_by',
            field=models.ManyToManyField(blank=0, related_name='disliked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
